name: Build and Deploy Docs

on:
  push:
    branches: [ main ]  # or whatever your default branch is

permissions:
  contents: write  # needed for gh-pages push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install sphinx
          # if you have extras:
          # pip install -r requirements.txt

      - name: Build Sphinx docs
        run: make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

